Warehouse Delay & Damage Analytics

Python Data Cleaning & Feature Engineering

Import Required Libraries

In [11]:
import pandas as pd

Load Dataset

In [13]:
df = pd.read_csv("Warehouse Delay & Damage Analytics Dataset.csv")

In [15]:
df

,delivery_id,delivery_partner,package_type,vehicle_type,delivery_mode,region,weather_condition,distance_km,package_weight_kg,delivery_time_hours,...,delayed,delivery_status,delivery_rating,delivery_cost,warehouse_id,warehouse_name,shift,damage_status,delay_reason,damage_cost
0,1,delhivery,automobile parts,bike,same day,west,clear,297.0,46.96,13.2,...,yes,delayed,3,782.40,WH100,Mumbai Warehouse,Evening,Safe,Weather,0
1,2,xpressbees,cosmetics,ev van,express,central,cold,89.6,47.39,4.0,...,no,delivered,4,547.18,WH101,Pune Warehouse,Evening,Safe,No Major Issue,0
2,3,shadowfax,groceries,truck,two day,east,rainy,273.5,26.89,7.9,...,no,delivered,4,823.60,WH102,Bangalore Warehouse,Evening,Safe,No Major Issue,0
3,4,dhl,electronics,ev van,same day,east,cold,269.7,12.69,12.2,...,yes,failed,1,815.19,WH103,Delhi Warehouse,Night,Damaged,Vehicle Breakdown,226
4,5,dhl,clothing,van,two day,north,foggy,256.7,37.02,8.2,...,no,delivered,1,774.82,WH104,Hyderabad Warehouse,Evening,Safe,No Major Issue,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,24996,dhl,furniture,scooter,two day,east,foggy,80.7,3.65,5.6,...,no,delivered,3,196.24,WH105,Chennai Warehouse,Evening,Safe,No Major Issue,0
24996,24997,ecom express,automobile parts,ev van,standard,west,clear,172.9,21.42,12.6,...,yes,delayed,4,545.98,WH106,Ahmedabad Warehouse,Evening,Safe,High Order Volume,0
24997,24998,ekart,clothing,scooter,same day,east,rainy,168.4,4.85,8.5,...,yes,delayed,3,468.32,WH100,Mumbai Warehouse,Evening,Safe,Weather,0
24998,24999,shadowfax,documents,ev van,standard,west,stormy,37.2,8.04,6.6,...,no,delivered,4,204.96,WH101,Pune Warehouse,Night,Safe,No Major Issue,0
24999,25000,blue dart,pharmacy,ev bike,two day,central,rainy,279.3,5.06,10.7,...,no,delivered,5,412.50,WH102,Bangalore Warehouse,Evening,Safe,No Major Issue,0

In [17]:
df.shape

(25000, 21)

In [19]:
df.head()

,delivery_id,delivery_partner,package_type,vehicle_type,delivery_mode,region,weather_condition,distance_km,package_weight_kg,delivery_time_hours,...,delayed,delivery_status,delivery_rating,delivery_cost,warehouse_id,warehouse_name,shift,damage_status,delay_reason,damage_cost
0,1,delhivery,automobile parts,bike,same day,west,clear,297.0,46.96,13.2,...,yes,delayed,3,782.40,WH100,Mumbai Warehouse,Evening,Safe,Weather,0
1,2,xpressbees,cosmetics,ev van,express,central,cold,89.6,47.39,4.0,...,no,delivered,4,547.18,WH101,Pune Warehouse,Evening,Safe,No Major Issue,0
2,3,shadowfax,groceries,truck,two day,east,rainy,273.5,26.89,7.9,...,no,delivered,4,823.60,WH102,Bangalore Warehouse,Evening,Safe,No Major Issue,0
3,4,dhl,electronics,ev van,same day,east,cold,269.7,12.69,12.2,...,yes,failed,1,815.19,WH103,Delhi Warehouse,Night,Damaged,Vehicle Breakdown,226
4,5,dhl,clothing,van,two day,north,foggy,256.7,37.02,8.2,...,no,delivered,1,774.82,WH104,Hyderabad Warehouse,Evening,Safe,No Major Issue,0

In [21]:
df.tail()

,delivery_id,delivery_partner,package_type,vehicle_type,delivery_mode,region,weather_condition,distance_km,package_weight_kg,delivery_time_hours,...,delayed,delivery_status,delivery_rating,delivery_cost,warehouse_id,warehouse_name,shift,damage_status,delay_reason,damage_cost
24995,24996,dhl,furniture,scooter,two day,east,foggy,80.7,3.65,5.6,...,no,delivered,3,196.24,WH105,Chennai Warehouse,Evening,Safe,No Major Issue,0
24996,24997,ecom express,automobile parts,ev van,standard,west,clear,172.9,21.42,12.6,...,yes,delayed,4,545.98,WH106,Ahmedabad Warehouse,Evening,Safe,High Order Volume,0
24997,24998,ekart,clothing,scooter,same day,east,rainy,168.4,4.85,8.5,...,yes,delayed,3,468.32,WH100,Mumbai Warehouse,Evening,Safe,Weather,0
24998,24999,shadowfax,documents,ev van,standard,west,stormy,37.2,8.04,6.6,...,no,delivered,4,204.96,WH101,Pune Warehouse,Night,Safe,No Major Issue,0
24999,25000,blue dart,pharmacy,ev bike,two day,central,rainy,279.3,5.06,10.7,...,no,delivered,5,412.50,WH102,Bangalore Warehouse,Evening,Safe,No Major Issue,0

In [23]:
df.columns

Index(['delivery_id', 'delivery_partner', 'package_type', 'vehicle_type',
       'delivery_mode', 'region', 'weather_condition', 'distance_km',
       'package_weight_kg', 'delivery_time_hours', 'expected_time_hours',
       'delayed', 'delivery_status', 'delivery_rating', 'delivery_cost',
       'warehouse_id', 'warehouse_name', 'shift', 'damage_status',
       'delay_reason', 'damage_cost'],
      dtype='object')

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 21 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   delivery_id          25000 non-null  int64
 1   delivery_partner     25000 non-null  object
 2   package_type         25000 non-null  object
 3   vehicle_type         25000 non-null  object
 4   delivery_mode        25000 non-null  object
 5   region               25000 non-null  object
 6   weather_condition    25000 non-null  object
 7   distance_km          25000 non-null  float64
 8   package_weight_kg    25000 non-null  float64
 9   delivery_time_hours  25000 non-null  float64
 10  expected_time_hours  25000 non-null  float64
 11  delayed              25000 non-null  object
 12  delivery_status      25000 non-null  object
 13  delivery_rating      25000 non-null  int64
 14  delivery_cost        25000 non-null  float64
 15  warehouse_id         25000 non-null  object
 16  warehouse_name       25000 non-null  object
 17  shift                25000 non-null  object
 18  damage_status        25000 non-null  object
 19  delay_reason         25000 non-null  object
 20  damage_cost          25000 non-null  int64
dtypes: float64(5), int64(3), object(13)
memory usage: 4.0+ MB

In [27]:
df['delivery_time_hours'].unique()

array([13.2,  4. ,  7.9, 12.2,  8.2,  3.6,  5. ,  3.8,  2.4,  7. ,  6.1,
       17.8,  5.1,  9.5,  5.8,  7.8, 19.2,  3. , 12.8,  9.6,  6.4, 16.2,
       13. ,  6.3, 11. ,  4.4,  9.4, 11.4,  8.4,  4.9,  9. ,  2.8, 10. ,
        6.6, 14.2,  2.6, 20.9,  8.8,  2.9,  8.6, 15. ,  3.5,  4.3,  5.4,
       11.2, 14.6,  3.1,  7.6, 10.5,  2.2, 25.8,  8.3,  9.8, 23.8,  9.1,
        5.6, 10.2,  3.2,  6.2,  7.2,  1.5,  4.6,  9.3, 15.2,  4.1, 14.8,
        5.2, 15.5, 11.6,  6. , 13.8,  6.7, 14.3, 17.6, 15.8,  6.8, 10.6,
        8.5,  7.7,  1.8,  4.5, 12.5,  8.1,  6.5,  7.4, 10.4,  4.2,  9.2,
        5.9, 14. , 10.9,  3.7, 14.1, 25.2,  2. ,  4.7,  8.7,  7.1, 19. ,
        8.9,  5.5, 11.7,  2.7, 13.6,  4.8, 11.9, 10.7, 21.4,  3.9, 11.8,
       17. ,  6.9,  7.5, 11.5, 12.9, 16. , 24.7, 12. ,  7.3,  8. , 13.5,
       15.4,  5.7, 16.6,  9.9, 18.2, 13.4, 18.8, 17.4,  3.3, 10.1,  2.3,
       18.4, 10.3, 21.8, 13.3,  9.7, 11.1, 10.8,  2.5, 21.3, 20.1, 16.1,
        3.4, 16.5,  5.3, 24.2, 16.8, 12.4, 12.6, 17.2,  1.6,  1.9, 20.4,
       17.7, 14.7, 11.3, 17.5, 15.6, 21.6, 22.3,  1. , 17.3, 20.8, 13.7,
       23.2, 24.4, 12.1, 16.4, 24.3, 12.3, 22.6, 13.9, 14.4, 12.7,  2.1,
       22.7,  1.7, 18.3,  1.4, 15.7, 21. , 18. , 27.2, 15.9, 17.9, 19.7,
       19.6, 20.6, 14.9, 18.6,  1.2, 15.3, 20.2, 15.1, 14.5, 16.3, 21.1,
       13.1, 19.9, 23. , 19.4, 20. , 20.3, 22.5, 21.2, 22.2, 25.4, 23.7,
       22.8, 19.8, 23.4, 17.1, 21.7, 22. , 18.5, 25.5, 18.7, 24. , 26. ,
       16.7, 16.9, 21.5, 19.3, 25. , 23.5, 26.2, 19.1, 18.1, 20.5, 22.4,
       19.5, 18.9, 22.9, 23.6, 25.3, 20.7, 24.6, 26.3, 24.5, 25.7,  1.3,
       22.1, 27. , 23.3, 24.8, 28.8, 21.9, 26.4,  1.1])

In [29]:
df['expected_time_hours'].unique()

array([ 9.3,  5.1,  7.5,  9.5,  4.2,  7.1,  4.8,  4.3,  3. ,  9.2,  6.7,
       10.1,  3.3, 11.4,  7.8,  7.9, 12.1,  3.5,  3.9, 10.4, 12.6, 10.5,
        6.6, 11.2, 14.1,  5.7, 11.7, 13.8,  5.6,  5.9,  5. ,  2.6,  8. ,
        8.1,  9.8,  3.2,  9.4,  2.2, 11.5,  9.1,  4.6,  2.9,  6.5,  9.7,
        6. ,  4.9, 12.4,  3.7,  6.4, 13.5,  8.7,  7.4, 13.2,  5.4,  5.3,
        4.4,  5.5, 11.1,  3.4,  4.5,  6.1,  7.3,  8.3,  8.5,  8.8,  2.4,
        6.8, 10.3, 13. ,  8.2, 13.4,  7.6, 12.8,  3.8,  4.7,  6.2,  5.2,
       10. , 11.8,  9.9,  2.7,  4. , 11.3, 13.3,  6.9,  7.7, 10.7, 11. ,
        7. ,  5.8,  7.2,  8.4, 13.9, 12.3, 10.6,  6.3, 11.9,  3.6,  8.9,
       14. , 13.6, 13.7, 12.5,  9. ,  9.6, 10.8, 15.2, 12.7, 12. , 10.9,
       12.2,  1.8, 10.2,  2.3,  2. ,  2.5, 12.9,  3.1, 14.4,  4.1,  2.1,
        8.6,  2.8, 14.2, 14.9, 14.6,  1.7, 14.5, 11.6,  1.9, 13.1, 14.8,
       14.7, 14.3, 15.6, 15. ,  1.6, 15.1, 15.5,  1.5, 15.3])

In [31]:
df.isnull().sum()

delivery_id            0
delivery_partner       0
package_type           0
vehicle_type           0
delivery_mode          0
region                 0
weather_condition      0
distance_km            0
package_weight_kg      0
delivery_time_hours    0
expected_time_hours    0
delayed                0
delivery_status        0
delivery_rating        0
delivery_cost          0
warehouse_id           0
warehouse_name         0
shift                  0
damage_status          0
delay_reason           0
damage_cost            0
dtype: int64

In [33]:
df.duplicated().sum()

0

In [35]:
df['delayed'].unique()

array(['yes', 'no'], dtype=object)

In [37]:
df['delayed']=df['delayed'].str.title()

In [41]:
df['delayed']

0        Yes
1         No
2         No
3        Yes
4         No
        ...
24995     No
24996    Yes
24997    Yes
24998     No
24999     No
Name: delayed, Length: 25000, dtype: object

In [43]:
df['delivery_status'].unique()

array(['delayed', 'delivered', 'failed'], dtype=object)

In [45]:
df['delivery_status']=df['delivery_status'].str.title()

In [47]:
df['delivery_status']

0          Delayed
1        Delivered
2        Delivered
3           Failed
4        Delivered
           ...
24995    Delivered
24996      Delayed
24997      Delayed
24998    Delivered
24999    Delivered
Name: delivery_status, Length: 25000, dtype: object

In [49]:
df['weather_condition'].unique()

array(['clear', 'cold', 'rainy', 'foggy', 'hot', 'stormy'], dtype=object)

In [51]:
df['weather_condition']=df['weather_condition'].str.title()

In [53]:
df['weather_condition']

0         Clear
1          Cold
2         Rainy
3          Cold
4         Foggy
          ...
24995     Foggy
24996     Clear
24997     Rainy
24998    Stormy
24999     Rainy
Name: weather_condition, Length: 25000, dtype: object

In [55]:
df['shift'].unique()

array(['Evening', 'Night', 'Morning'], dtype=object)

In [57]:
df['shift']=df['shift'].str.title()

In [59]:
df['shift']

0        Evening
1        Evening
2        Evening
3          Night
4        Evening
          ...
24995    Evening
24996    Evening
24997    Evening
24998      Night
24999    Evening
Name: shift, Length: 25000, dtype: object

In [61]:
df['delayed'].value_counts()

delayed
No     15877
Yes     9123
Name: count, dtype: int64

In [63]:
df['delivery_status'].value_counts()

delivery_status
Delivered    15877
Delayed       5682
Failed        3441
Name: count, dtype: int64

In [65]:
df['weather_condition'].value_counts()

weather_condition
Foggy     4219
Stormy    4198
Rainy     4171
Cold      4158
Hot       4130
Clear     4124
Name: count, dtype: int64

In [67]:
df['shift'].value_counts()

shift
Morning    8370
Evening    8328
Night      8302
Name: count, dtype: int64

Feature Engineering

In [70]:
#SLA = Service Level Agreement
import numpy as np

In [72]:
df['sla_status']=np.where(
    df['delivery_time_hours']>df['expected_time_hours'],
    'Breached SLA',
    'Within SLA'
)

In [74]:
df['sla_status'].value_counts()

sla_status
Within SLA      15255
Breached SLA     9745
Name: count, dtype: int64

In [76]:
df[['delivery_time_hours',
    'expected_time_hours',
    'sla_status']].head(10)

   delivery_time_hours  expected_time_hours    sla_status
0                 13.2                  9.3  Breached SLA
1                  4.0                  5.1    Within SLA
2                  7.9                  9.3    Within SLA
3                 12.2                  7.5  Breached SLA
4                  8.2                  9.5    Within SLA
5                  3.6                  4.2    Within SLA
6                  5.0                  7.1    Within SLA
7                  3.8                  4.8    Within SLA
8                  4.0                  4.3    Within SLA
9                  2.4                  3.0    Within SLA

Final Dataset Check

In [84]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 22 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   delivery_id          25000 non-null  int64
 1   delivery_partner     25000 non-null  object
 2   package_type         25000 non-null  object
 3   vehicle_type         25000 non-null  object
 4   delivery_mode        25000 non-null  object
 5   region               25000 non-null  object
 6   weather_condition    25000 non-null  object
 7   distance_km          25000 non-null  float64
 8   package_weight_kg    25000 non-null  float64
 9   delivery_time_hours  25000 non-null  float64
 10  expected_time_hours  25000 non-null  float64
 11  delayed              25000 non-null  object
 12  delivery_status      25000 non-null  object
 13  delivery_rating      25000 non-null  int64
 14  delivery_cost        25000 non-null  float64
 15  warehouse_id         25000 non-null  object
 16  warehouse_name       25000 non-null  object
 17  shift                25000 non-null  object
 18  damage_status        25000 non-null  object
 19  delay_reason         25000 non-null  object
 20  damage_cost          25000 non-null  int64
 21  sla_status           25000 non-null  object
dtypes: float64(5), int64(3), object(14)
memory usage: 4.2+ MB

In [86]:
print("Rows :", df.shape[0])
print("Columns :",df.shape[1])
print("Missing Values :",df.isnull().sum())
print("Duplicate ROwa :",df.duplicated().sum())

Rows : 25000
Columns : 22
Missing Values : delivery_id            0
delivery_partner       0
package_type           0
vehicle_type           0
delivery_mode          0
region                 0
weather_condition      0
distance_km            0
package_weight_kg      0
delivery_time_hours    0
expected_time_hours    0
delayed                0
delivery_status        0
delivery_rating        0
delivery_cost          0
warehouse_id           0
warehouse_name         0
shift                  0
damage_status          0
delay_reason           0
damage_cost            0
sla_status             0
dtype: int64
Duplicate ROwa : 0

In [90]:
df.to_csv("warehouse_analytics.csv", index=False)

Ddataset sending to sql

In [93]:
pip install sqlalchemy pymysql

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: sqlalchemy in c:\programdata\anaconda3\lib\site-packages (2.0.34)
Requirement already satisfied: pymysql in c:\users\ashlesha ahirkar\appdata\roaming\python\python312\site-packages (1.2.0)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\programdata\anaconda3\lib\site-packages (from sqlalchemy) (4.11.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\programdata\anaconda3\lib\site-packages (from sqlalchemy) (3.0.1)
Note: you may need to restart the kernel to use updated packages.

In [95]:
import pandas as pd
from sqlalchemy import create_engine

# Load cleaned CSV
df = pd.read_csv("warehouse_analytics.csv")

# AWS RDS Connection
username = "admin"
password = "warehouse_1203"
host = "warehouse-db.c1ia8mwkso7r.ap-south-1.rds.amazonaws.com"
port = 3306
database = "warehouse_analytics"

engine = create_engine(
    f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}"
)

# Upload data
df.to_sql(
    name="warehouse_operations",
    con=engine,
    if_exists="append",
    index=False
)

print("Data uploaded successfully!")

Data uploaded successfully!